#!/bin/bash -e
source "${OPENSHIFT_RUBY_DIR}/lib/servers"

function start() {
  unicorn -D --env $RACK_ENV
}

function stop() {
  ps aux | grep unicorn | awk '{print $2}' | xargs kill -9
}

function restart() {
  stop() && start()
}

case "$1" in
  start)    start ;;
  stop)     stop ;;
  restart)  restart ;;
  *)        exit 0 ;;
esac
